services:
  - type: web
    name: terns-exim
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production

  - type: web
    name: terns-exim-api
    env: python
    buildCommand: pip install -r crm/requirements.txt
    startCommand: gunicorn crm.app:app --workers 2 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
